apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
  labels:
{{ toYaml .Values.nginx.labels | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.nginx.containerPorts.http }}
  selector:
{{ toYaml .Values.nginx.labels | nindent 4 }}
